[versions]
activityComposeVersion = "1.10.1"
agp = "8.8.2"
#noinspection GradleDependency
androidxComposeBom = "2025.03.00"
androidxLifecycleRuntimeKtx = "2.8.7"
bcrypt = "0.9.0"
#noinspection GradleDependency
bcryptVersion = "0.10.2"
composeBomVersion = "2025.03.00"
#noinspection GradleDependency
converterGson = "2.9.0"
foundation = "1.7.8"
gson = "2.10.1"
jbcrypt = "0.4"
jjwtJackson = "0.11.5"
kotlin = "2.0.0"
#noinspection GradleDependency
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxSerializationJson = "1.7.3"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
#noinspection GradleDependency
composeBom = "2025.03.00"
lifecycleRuntimeKtxVersion = "2.8.7"
#noinspection GradleDependency
loggingInterceptor = "4.9.1"
material = "1.7.8"
#noinspection GradleDependency
material3 = "1.3.1"
materialIconsExtended = "1.7.8"
#noinspection GradleDependency
retrofit = "2.9.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
roomRuntime = "2.6.1"
#noinspection GradleDependency
runtimeLivedata = "1.7.8"
#noinspection GradleDependency
ui = "1.7.8"
#noinspection GradleDependency
benchmarkMacro = "1.3.3"

[libraries]
#noinspection SimilarGradleDependency
androidx-activity-compose-v182 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
#noinspection SimilarGradleDependency
androidx-compose-bom-v20230800 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
#noinspection SimilarGradleDependency
androidx-compose-bom-v20250300 = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
#noinspection SimilarGradleDependency
androidx-lifecycle-runtime-ktx-v262 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeKtx" }
#noinspection SimilarGradleDependency
androidx-lifecycle-runtime-ktx-v270 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
bcrypt-v0102 = { module = "at.favre.lib:bcrypt", version.ref = "bcryptVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwtJackson" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwtJackson" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwtJackson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#noinspection SimilarGradleDependency
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#noinspection SimilarGradleDependency
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#noinspection SimilarGradleDependency
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro", version.ref = "benchmarkMacro" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }